---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create S3 bucket into ap-south-1"

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: my-first-bucket
