---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create First Elastic Block Store volume"
Resources:
  MyFirstEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      Tags: 
        - Key: Name
          Value: FirstEBSCFT
      AvailabilityZone: "ap-south-1a"
      Size: 1
      VolumeType: gp3