---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create First Elastic Block Store volume"
Resources:
  MyFirstEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      Tags: 
        - myfirsttag
      AvailabilityZone: "ap-south-1a"
      Size: 1GiBs
      VolumeType: gp2 