---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating ec2 instance alone"
Resources:
  Ec2FromCFT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-022ce6f32988af5fa"
      AvailabilityZone: "ap-south-1a"
      InstanceType: "t2.micro"
