---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating ec2 instance alone"
Resources:
  Ec2FromCFT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-1258965"
      AvailabilityZone: "ap-south-1a"
      InstanceType: "t2.micro"
      Tags:
      - Key: Name
        Value: EC2InstanceFromCFT