---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Launch Template"
Resources:
  MyFirstLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-0e1d06225679bc1c5
        InstanceType: "t2.micro"
        AvailabilityZone: "ap-south-1b"
      LaunchTemplateName: FirstLaunchTemplateCFT
