---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating the security groups"
Resources:
  MyFirstSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH connection for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: SSHSecurityGroup