---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Auto Scaling groups"

Parameters:
  ASGName:
   Description: "AutoScaling Name"
   Type: String
   Default: AutoScalingUsingCFT


  AZNames:
    Description: "ASG Availability Zone"
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: ap-south-1a

  LatestAMIId:
      Description: "Region specific image from the Parameters store"
      Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
      Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  InstanceType:
      Description: "Amazon EC2 Instance Type for the instances"
      Type: String
      AllowedValues:
        - t2.micro
        - t3.small
        - t3.medium
      Default: t2.micro

  Subnets:
        Description: "A list of subnets for the auto scaling groups"
        Type: List<AWS::EC2::Subnet::Id>

Resources:
  MyLaunchTemplateExample:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-Launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAMIId
        InstanceType: !Ref InstanceType
  
  MyFirstASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplateExample
        Version: !GetAtt MyLaunchTemplateExample.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      VPCZoneIdentifier: !Ref Subnets



      
